### PR TITLE
Webpack Overwrite Settings (Fix #46)

### LINKED ISSUE #46: Cannot rename build file from webpack override
I want to rename build file: **direflowBundle.js**.
Like this I have error: __ENOENT: no such file or directory, open '/home/lioshi/gitlibs/booki/eilep-booki/build/customeName.js'__

```js
const webpackConfig = require('direflow-component/config-overrides');

/**
 * Webpack configuration for Direflow Component
 * Additional webpack plugins / overrides can be provided here
 */
module.exports = (config, env) => ({
  ...webpackConfig(config, env),
  output: customOutput(config.output)


});

const customOutput = (output) => {
  const { checkFilename, ...newOutput } = output;

  return {
    ...newOutput,
    filename: 'customeName.js',
    chunkFilename: 'vendor.js',
  };
};
```

### PR DESCRIPTION
**Pull request by JohnDeved**
**What does this pull request introduce? Please describe**  
fixes #46 

**Example**  
```js
module.exports = (config, env) => ({
  ...webpackConfig(config, env, {filename: 'myBundle.js'})
})
```

**Version**  
3.2.1
  
Did you remember to remember to update the version of Direflow as explained here:  
https://github.com/Silind-Software/direflow/blob/master/CONTRIBUTING.md#version

### CODE REVIEW

File: packages/direflow-component/src/config/config-overrides.ts [hunk 1]
```diff
@@ -5,14 +5,21 @@ import fs from 'fs';
...
 import { PromiseTask } from 'event-hooks-webpack-plugin/lib/tasks';
 
-module.exports = function override(config: any, env: string): any {
+interface IOptions {
+  filename?: string;
+  chunkFilename?: string;
+}
+
+module.exports = function override(config: any, env: string, options?: IOptions): any {
+  const { filename = 'direflowBundle.js', chunkFilename = 'vendor.js' } = options || {};
```
Comment (Silind) [inline packages/direflow-component/src/config/config-overrides.ts]: I think this line may be a bit confusing.
To make the intention more clear, I would prefer the more verbose version:
```typescript
const filename = options?.filename || 'direflowBundle.js';
const chuckFileName = options?.chunkFilename || 'vendor.js';
```
What do you think? 🙂

Comment (JohnDeved) [reply packages/direflow-component/src/config/config-overrides.ts]: sure if you prefer that

Comment (JohnDeved) [reply packages/direflow-component/src/config/config-overrides.ts]: changes have been pushed
