### PR TITLE
Fix #64

### LINKED ISSUE #64: Properties should be unique for each instance of the component on the page
**Describe the bug**  
Property value is used by multiple instances of the component on the same page.

**To reproduce**  
1. Create a new component with `direflow create` ('test' is the name)
2. Duplicate `<test-component></test-component>` in `index.html`
3. Add `componentTitle` attribute to the first instant of the component
4. Load the page and see that specified title is used by both components

**Expected behavior**  
First component should show the specified title while the second one should show the default.

**Screenshots**  
Screen Shot 2020-02-03 at 14 00 17

### PR DESCRIPTION
**Pull request by Silind**
**What does this pull request introduce? Please describe**  
This PR fixes issue #64 

**How did you verify that your changes work as expected? Please describe**  
Created a new Direflow Setup and verified the desired fix.

**Example**  
Please describe how we can try out your changes  
1. Create a new Direflow Setup
2. Add two instances of the same component in `index.html`
3. Set an attribute on one instance
4. Verify that the change only reflects on that instance
5. Verify that the same behavior applies to properties as well

**Version**  
3.2.6

### CODE REVIEW

File: packages/direflow-component/src/WebComponentFactory.tsx [hunk 1]
```diff
@@ -192,10 +195,9 @@ class WebComponentFactory {
       /**
        * Generate react props based on properties and attributes.
        */
-      // eslint-disable-next-line class-methods-use-this
       private reactProps(): any {
-        factory.reflectPropertiesToAttributes();
-        return { ...factory.componentProperties };
+        this.syncronizePropertiesAndAttributes();
+        return { ...this._properties };
```
Comment (JohnDeved) [inline packages/direflow-component/src/WebComponentFactory.tsx]: this won't lead to another shallow copy issue, will it?

File: packages/direflow-component/src/WebComponentFactory.tsx [hunk 2]
```diff
@@ -60,6 +63,7 @@ class WebComponentFactory {
 
     return class extends HTMLElement {
       private _application: JSX.Element | undefined;
+      private _properties: any = clonedeep(factory.componentProperties);
```
Comment (JohnDeved) [inline packages/direflow-component/src/WebComponentFactory.tsx]: dont very much like the bland any time here. 
would preffer `{ [key: string]: any }` since object?

**Comment by JohnDeved** [comment]
otherwise seems good to me, will approve after my local test & when review resolved 👍

File: packages/direflow-component/src/WebComponentFactory.tsx (hunk 1 above)
Comment (Silind) [reply packages/direflow-component/src/WebComponentFactory.tsx]: It won't - but can actually be returned directly without the spread.
I'll fix this in the morning 👍

File: packages/direflow-component/src/WebComponentFactory.tsx (hunk 2 above)
Comment (Silind) [reply packages/direflow-component/src/WebComponentFactory.tsx]: Sure, we can go with `{ [key: string]: any }`

**Comment by Silind** [comment]
Nice catch! Yeah, something went wrong here.

**Comment by JohnDeved** [comment]
local test was successful 👍 
image
